### ISSUE TITLE
[meta] Rust LSP Types

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/lsprotocol#164]
- [x] https://github.com/microsoft/lsprotocol/issues/157
- [x] https://github.com/microsoft/lsprotocol/issues/158
- [x] https://github.com/microsoft/lsprotocol/issues/159
- [x] https://github.com/microsoft/lsprotocol/issues/160
- [x] https://github.com/microsoft/lsprotocol/issues/161
- [x] https://github.com/microsoft/lsprotocol/issues/162
- [x] https://github.com/microsoft/lsprotocol/issues/163

Reference: https://github.com/microsoft/lsprotocol/issues/151
